name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Restic
      run: |
        sudo apt-get update
        sudo apt-get install -y restic

    - name: Build
      run: make build

    - name: Run tests
      run: make test
      env:
        # Tests will be skipped without these environment variables
        TEST_S3_ENDPOINT: ${{ secrets.TEST_S3_ENDPOINT }}
        TEST_RESTIC_REPOSITORY: ${{ secrets.TEST_RESTIC_REPOSITORY }}
        TEST_RESTIC_PASSWORD: ${{ secrets.TEST_RESTIC_PASSWORD }}
        TEST_AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        TEST_AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}

  build-and-push:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        make docker-build PLUGIN_IMAGE=${{ secrets.DOCKER_REGISTRY }}/cnpg-restic-plugin
        make docker-push PLUGIN_IMAGE=${{ secrets.DOCKER_REGISTRY }}/cnpg-restic-plugin
